version: "3.3"
services:
  service1:
    build:
      context: /project/ConsulDemo/MicroService.Demo
    image: composecoreconsulv1.00
    ports:
      - 9001:80/tcp
    volumes:
      - /project/ConsulDemo/config/appsettings/appsettings9001.json:/app/appsettings.json
  service2:
    image: composecoreconsulv1.00
    ports:
      - 9002:80/tcp
    command: ["dotnet", "/app/MicroService.Demo.ServiceInstance.dll"]
    volumes:
      - /project/ConsulDemo/config/appsettings/appsettings9002.json:/app/appsettings.json
  service3:
    image: composecoreconsulv1.00
    ports:
      - 9003:80/tcp
    command: ["dotnet", "/app/MicroService.Demo.ServiceInstance.dll"]
    volumes:
      - /project/ConsulDemo/config/appsettings/appsettings9003.json:/app/appsettings.json
  nginx:
    image: nginx:latest
    ports:
      - 9080:80/tcp
    volumes:
      - /project/ConsulDemo/config/nginx.conf:/etc/nginx/nginx.conf
