version: "3.3"
services:
  gw6297:
    build:
      context: /project/ConsulWithGateway/MicroService.Demo
    image: composegateway
    ports:
      - 6297:80/tcp
  gw6298:
    image: composegateway
    ports:
      - 6298:80/tcp
    command: ["dotnet", "/app/MicroService.Demo.Gateway.dll"]
  gw6299:
    image: composegateway
    ports:
      - 6299:80/tcp
    command: ["dotnet", "/app/MicroService.Demo.Gateway.dll"]
  gwnginx:
    image: nginx:latest
    ports:
      - 8083:80/tcp
    volumes:
      - /project/ConsulWithGateway/gatewaynginx/nginx.conf:/etc/nginx/nginx.conf
